#
# update ServerConfig set Value='http://apollo-configservice-dev:8080/eureka/' where `key`='eureka.service.url'
version: "3"
services:
 redis-dev:
  image: redis

 mysql-dev:
  image: mysql
  environment:
   - MYSQL_ROOT_PASSWORD=123456
  volumes:
      - ./scripts/sql:/sql

#========== Apollo ===============
 apollo-configservice-dev:
    image: rcntech/apollo-configservice:v1.2.0
    environment:
     DATASOURCES_URL: "jdbc:mysql://mysql-dev:3306/ApolloConfigDB?characterEncoding=utf8"
     DATASOURCES_USERNAME: root
     DATASOURCES_PASSWORD: 123456
     ENV: "dev"
    expose:
     - "8080"
    ports:
     - 8080:8080
    depends_on:
     - "mysql-dev"
 apollo-adminservice-dev:
    image: rcntech/apollo-adminservice:v1.2.0
    environment:
     DATASOURCES_URL: "jdbc:mysql://mysql-dev:3306/ApolloConfigDB?characterEncoding=utf8"
     DATASOURCES_USERNAME: root
     DATASOURCES_PASSWORD: 123456
     ENV: "dev"
    expose:
     - "8080"
    depends_on:
     - "mysql-dev"
     - "apollo-configservice-dev"
 apollo-portal:
     image: rcntech/apollo-portal:v1.2.0
     environment:
      DEV_META_SERVICE_NAME: apollo-configservice-dev
      DATASOURCES_URL: "jdbc:mysql://mysql-dev:3306/ApolloPortalDB?characterEncoding=utf8"
      DATASOURCES_USERNAME: root
      DATASOURCES_PASSWORD: 123456
     ports:
      - 8070:8070
     depends_on:
      - "mysql-dev"
      - "apollo-configservice-dev"
      - "apollo-adminservice-dev"

#========== Sms Service ===============
 sms:
  build:
    context: ./
    dockerfile: scripts/docker/Dockerfile
    args:
      APP_PROJECT_NAME: "AppBubbleSmsService"
  environment:
   APOLLO_META: "http://apollo-configservice-dev:8080"
   APP_PROJECT_NAME: "AppBubbleSmsService"
   APP_PROTO_PACKAGE: sms
   APP_GATEWAY_SERVICE: SmsService


   ENV: dev
  expose:
   - "8080"
   - "8090"
  ports:
   - "8088:8080"
   - "8099:8090"
  depends_on:
#   - "apollo-portal"
#   - "mysql-dev"
   - "redis-dev"

