#
# update ServerConfig set Value='http://apollo-configservice-dev:8080/eureka/' where `key`='eureka.service.url'
version: "3"
services:
 envoy:
  image: envoyproxy/envoy:latest
  volumes:
    - ./scripts/envoy/envoy.yaml:/etc/envoy/envoy.yaml
    - ./scripts/envoy/app.protobin:/app/app.protobin
  ports:
   - "8090:8090"

 redis-dev:
  image: redis

 mysql-dev:
  image: mysql
  environment:
   - MYSQL_ROOT_PASSWORD=123456
  volumes:
      - ./scripts/sql:/sql

#========== ELK  ========
 logstash:
  image: logstash:6.6.2
  expose:
    - "4560"
  volumes:
    - ./scripts/elk/logstash/pipeline:/usr/share/logstash/pipeline/
    - ./scripts/elk/logstash/logstash.yaml:/usr/share/logstash/config/logstash.yml
  depends_on:
    - elasticsearch

 elasticsearch:
  image: elasticsearch:6.6.2
  volumes:
   - ./scripts/elk/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  environment:
   - bootstrap.memory_lock=true
   - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  ulimits:
   memlock:
    soft: -1
    hard: -1
  expose:
    - 9200
    - 9300

 kibana:
  image: kibana:6.6.2
  volumes:
   - ./scripts/elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
  expose:
    - 5601
  ports:
    - "5601:5601"


#========== Apollo ===============
 apollo-configservice-dev:
    image: rcntech/apollo-configservice:v1.2.0
    environment:
     DATASOURCES_URL: "jdbc:mysql://mysql-dev:3306/ApolloConfigDB?characterEncoding=utf8"
     DATASOURCES_USERNAME: root
     DATASOURCES_PASSWORD: 123456
     ENV: "dev"
    expose:
     - "8080"
    ports:
     - 8080:8080
    depends_on:
     - "mysql-dev"
 apollo-adminservice-dev:
    image: rcntech/apollo-adminservice:v1.2.0
    environment:
     DATASOURCES_URL: "jdbc:mysql://mysql-dev:3306/ApolloConfigDB?characterEncoding=utf8"
     DATASOURCES_USERNAME: root
     DATASOURCES_PASSWORD: 123456
     ENV: "dev"
    expose:
     - "8080"
    depends_on:
     - "mysql-dev"
     - "apollo-configservice-dev"
 apollo-portal:
     image: rcntech/apollo-portal:v1.2.0
     environment:
      DEV_META_SERVICE_NAME: apollo-configservice-dev
      DATASOURCES_URL: "jdbc:mysql://mysql-dev:3306/ApolloPortalDB?characterEncoding=utf8"
      DATASOURCES_USERNAME: root
      DATASOURCES_PASSWORD: 123456
     ports:
      - 8070:8070
     depends_on:
      - "mysql-dev"
      - "apollo-configservice-dev"
      - "apollo-adminservice-dev"

#========== Sms Service ===============
 sms:
  build:
    context: ./
    dockerfile: scripts/docker/Dockerfile
    args:
      APP_PROJECT_NAME: "AppBubbleSmsService"
  environment:
   APOLLO_META: "http://apollo-configservice-dev:8080"
   APP_PROJECT_NAME: "AppBubbleSmsService"
   ENV: dev
  expose:
   - "8080"
   - "8090"
  depends_on:
#   - "apollo-portal"
#   - " "
   - "redis-dev"
   - "logstash"
 user:
  build:
    context: ./
    dockerfile: scripts/docker/Dockerfile
    args:
      APP_PROJECT_NAME: "AppBubbleUserService"
  environment:
   APOLLO_META: "http://apollo-configservice-dev:8080"
   APP_PROJECT_NAME: "AppBubbleUserService"
   ENV: dev

  expose:
   - "8080"
   - "8090"

  depends_on:
#    - "apollo-portal"
    - "mysql-dev"
    - "logstash"

 relation:
  build:
    context: ./
    dockerfile: scripts/docker/Dockerfile
    args:
      APP_PROJECT_NAME: "AppBubbleUserRelationService"
  environment:
   APOLLO_META: "http://apollo-configservice-dev:8080"
   APP_PROJECT_NAME: "AppBubbleUserRelationService"
   ENV: dev

  expose:
   - "8080"
   - "8090"

  depends_on:
#    - "apollo-portal"
    - "mysql-dev"
    - "logstash"

