#run --rm --network apollo_default -e ENV=dev --link apollo_apollo-configservice-dev_1:apollo-configservice bubble/sms-service:0.0.1-SNAPSHOT
# update ServerConfig set Value='http://apollo-configservice.apollo:8080/eureka/' where `key`='eureka.service.url'
version: "3"
services:
 redis-dev:
  image: redis

 mysql-dev:
  image: mysql
  environment:
   - MYSQL_ROOT_PASSWORD=123456
  volumes:
      - ../sql:/sql

#========== Apollo ===============
 apollo-configservice-dev:
    image: rcntech/apollo-configservice:v1.2.0
    environment:
     DATASOURCES_URL: "jdbc:mysql://mysql-dev:3306/ApolloConfigDB?characterEncoding=utf8"
     DATASOURCES_USERNAME: root
     DATASOURCES_PASSWORD: 123456
     ENV: "dev"
    expose:
     - "8080"
    ports:
     - 8080:8080
    depends_on:
     - "mysql-dev"
 apollo-adminservice-dev:
    image: rcntech/apollo-adminservice:v1.2.0
    environment:
     DATASOURCES_URL: "jdbc:mysql://mysql-dev:3306/ApolloConfigDB?characterEncoding=utf8"
     DATASOURCES_USERNAME: root
     DATASOURCES_PASSWORD: 123456
     ENV: "dev"
    expose:
     - "8080"
    depends_on:
     - "mysql-dev"
     - "apollo-configservice-dev"
 apollo-portal:
     image: rcntech/apollo-portal:v1.2.0
     environment:
      DEV_META_SERVICE_NAME: apollo-configservice-dev
      DATASOURCES_URL: "jdbc:mysql://mysql-dev:3306/ApolloPortalDB?characterEncoding=utf8"
      DATASOURCES_USERNAME: root
      DATASOURCES_PASSWORD: 123456
     ports:
      - 8070:8070
     depends_on:
      - "mysql-dev"
      - "apollo-configservice-dev"
      - "apollo-adminservice-dev"

#========== Sms Service ===============
 sms:
  build:
    context: /Users/yjwfn/development/web-project/AppBubbleBackend/AppBubbleSmsService
    args:
     APP_JAR_FILE: "sms-0.0.1-SNAPSHOT.jar"
  environment:
   APOLLO_META: "http://apollo-configservice-dev:8080"
   ENV: dev
  expose:
   - "8080"
  ports:
   - "8088:8080"
  depends_on:
   - "apollo-portal"
   - "mysql-dev"
   - "redis-dev"

