mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bubble.user.entity



spring:
  datasource:
    url: jdbc:mysql://mysql-dev:3306/bubble_video?characterEncoding=utf8
    username: root
    password: 123456

logging:
  level:
    user: trace
    root: info
  group:
   user: com.bubble.user

