server:
  port: 8080

# Spring
spring:
#  application:
#    name: AppBubbleSmsService

  messages:
    basename: i18n/messages
    encoding: UTF-8

# Apollo
app:
 id: 1547393624

apollo:
 bootstrap:
  enabled: true
  namespaces: application


# Mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml



